// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/go-swagger/go-swagger/examples/tutorials/todo-list/server-complete/models"
)

// FindOnetodosOKCode is the HTTP code returned for type FindOnetodosOK
const FindOnetodosOKCode int = 200

/*FindOnetodosOK OK

swagger:response findOnetodosOK
*/
type FindOnetodosOK struct {

	/*
	  In: Body
	*/
	Payload *models.Item `json:"body,omitempty"`
}

// NewFindOnetodosOK creates FindOnetodosOK with default headers values
func NewFindOnetodosOK() *FindOnetodosOK {

	return &FindOnetodosOK{}
}

// WithPayload adds the payload to the find onetodos o k response
func (o *FindOnetodosOK) WithPayload(payload *models.Item) *FindOnetodosOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find onetodos o k response
func (o *FindOnetodosOK) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindOnetodosOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FindOnetodosDefault error

swagger:response findOnetodosDefault
*/
type FindOnetodosDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindOnetodosDefault creates FindOnetodosDefault with default headers values
func NewFindOnetodosDefault(code int) *FindOnetodosDefault {
	if code <= 0 {
		code = 500
	}

	return &FindOnetodosDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find onetodos default response
func (o *FindOnetodosDefault) WithStatusCode(code int) *FindOnetodosDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find onetodos default response
func (o *FindOnetodosDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find onetodos default response
func (o *FindOnetodosDefault) WithPayload(payload *models.Error) *FindOnetodosDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find onetodos default response
func (o *FindOnetodosDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindOnetodosDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
