// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindOnetodosHandlerFunc turns a function with the right signature into a find onetodos handler
type FindOnetodosHandlerFunc func(FindOnetodosParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindOnetodosHandlerFunc) Handle(params FindOnetodosParams) middleware.Responder {
	return fn(params)
}

// FindOnetodosHandler interface for that can handle valid find onetodos params
type FindOnetodosHandler interface {
	Handle(FindOnetodosParams) middleware.Responder
}

// NewFindOnetodos creates a new http.Handler for the find onetodos operation
func NewFindOnetodos(ctx *middleware.Context, handler FindOnetodosHandler) *FindOnetodos {
	return &FindOnetodos{Context: ctx, Handler: handler}
}

/*FindOnetodos swagger:route GET /{id} todos findOnetodos

FindOnetodos find onetodos API

*/
type FindOnetodos struct {
	Context *middleware.Context
	Handler FindOnetodosHandler
}

func (o *FindOnetodos) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindOnetodosParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
