// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// OnetodosHandlerFunc turns a function with the right signature into a onetodos handler
type OnetodosHandlerFunc func(OnetodosParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OnetodosHandlerFunc) Handle(params OnetodosParams) middleware.Responder {
	return fn(params)
}

// OnetodosHandler interface for that can handle valid onetodos params
type OnetodosHandler interface {
	Handle(OnetodosParams) middleware.Responder
}

// NewOnetodos creates a new http.Handler for the onetodos operation
func NewOnetodos(ctx *middleware.Context, handler OnetodosHandler) *Onetodos {
	return &Onetodos{Context: ctx, Handler: handler}
}

/*Onetodos swagger:route GET /{id} todos onetodos

Onetodos onetodos API

*/
type Onetodos struct {
	Context *middleware.Context
	Handler OnetodosHandler
}

func (o *Onetodos) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewOnetodosParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
