// Code generated by go-swagger; DO NOT EDIT.

package wanclouds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindoneHandlerFunc turns a function with the right signature into a findone handler
type FindoneHandlerFunc func(FindoneParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindoneHandlerFunc) Handle(params FindoneParams) middleware.Responder {
	return fn(params)
}

// FindoneHandler interface for that can handle valid findone params
type FindoneHandler interface {
	Handle(FindoneParams) middleware.Responder
}

// NewFindone creates a new http.Handler for the findone operation
func NewFindone(ctx *middleware.Context, handler FindoneHandler) *Findone {
	return &Findone{Context: ctx, Handler: handler}
}

/*Findone swagger:route GET /wan wanclouds findone

Findone findone API

*/
type Findone struct {
	Context *middleware.Context
	Handler FindoneHandler
}

func (o *Findone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindoneParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
