// Code generated by go-swagger; DO NOT EDIT.

package wanclouds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/go-swagger/go-swagger/examples/tutorials/todo-list/server-complete/models"
)

// FindoneOKCode is the HTTP code returned for type FindoneOK
const FindoneOKCode int = 200

/*FindoneOK list the todo operations

swagger:response findoneOK
*/
type FindoneOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Item `json:"body,omitempty"`
}

// NewFindoneOK creates FindoneOK with default headers values
func NewFindoneOK() *FindoneOK {

	return &FindoneOK{}
}

// WithPayload adds the payload to the findone o k response
func (o *FindoneOK) WithPayload(payload []*models.Item) *FindoneOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the findone o k response
func (o *FindoneOK) SetPayload(payload []*models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindoneOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Item, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*FindoneDefault generic error response

swagger:response findoneDefault
*/
type FindoneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindoneDefault creates FindoneDefault with default headers values
func NewFindoneDefault(code int) *FindoneDefault {
	if code <= 0 {
		code = 500
	}

	return &FindoneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the findone default response
func (o *FindoneDefault) WithStatusCode(code int) *FindoneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the findone default response
func (o *FindoneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the findone default response
func (o *FindoneDefault) WithPayload(payload *models.Error) *FindoneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the findone default response
func (o *FindoneDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindoneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
