swagger: "2.0"
info:
  description: APPLICATION
  title: WANCLOUDS
  version: 1.0.0
consumes:
- application/io.goswagger.examples.todo-list.v1+json
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
paths:
  /:
    get:
      tags:
        - todos
      operationId: findTodos
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
                   
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/profile" 
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"

  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    get:
      tags:
        - todos
      operationId: onetodos
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/profile"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/profile"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"   
 
definitions:
 profile:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      email:
        type: string 
      
 error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
 
